DATAS SEGMENT
    X1 DB 4 DUP(?)
    X2 DB 4 DUP(?)
    X3 DB 5 DUP(?)
    X4 DB 0DH,0AH
DATAS ENDS

STACKS SEGMENT
    DB 100 DUP('STACK')
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MAIN PROC FAR
    MOV AX,DATAS
    MOV DS,AX
    MOV SI,OFFSET X1;输入4位到X1
    MOV DL,' '
    MOV AH,2H
    INT 21H
    MOV CX,4
NEXT:CALL KEYIN
    AND AL,0FH
    MOV [SI],AL
    INC SI
    LOOP NEXT   
    MOV SI,OFFSET X4
    MOV CX,2
HUANHANG:MOV DL,[SI];换行+回车
    MOV AH,2
    INT 21H
    INC SI
    LOOP HUANHANG
    MOV DL,2BH
    MOV AH,2H
    INT 21H
    MOV DI,OFFSET X2;输入4位到X2
    MOV CX,4
NEXT1:CALL KEYIN
    AND AL,0FH
    MOV [DI],AL
    INC DI
    LOOP NEXT1
    MOV SI,OFFSET X4
    MOV CX,2
HUANHANG1:MOV DL,[SI];换行+回车
    MOV AH,2
    INT 21H
    INC SI
    LOOP HUANHANG1
	MOV CX,6
HENGXIAN:MOV DL,'-'
	MOV AH,2H
	INT 21H
	LOOP HENGXIAN
	MOV SI,OFFSET X4
	MOV CX,2
HUANHANG2:MOV DL,[SI];换行+回车
    MOV AH,2
    INT 21H
    INC SI
    LOOP HUANHANG2
    MOV SI,OFFSET X1+3;运算部分
    MOV DI,OFFSET X2+3
    MOV BX,OFFSET X3+4
    MOV CX,4
    OR CX,CX
NEXT2:MOV AL,[SI]
    ADC AL,[DI]
    AAA
    MOV [BX],AL
    DEC SI
    DEC DI
    DEC BX
    LOOP NEXT2
    MOV AL,0
    ADC AL,0
    MOV [BX],AL
    MOV BX,OFFSET X3;显示部分
    MOV CX,4
NEXT3:MOV DL,[BX];高位为0则不显示
    CMP DL,0
    JNZ NEXT4;第一位不为零跳出循环1
    INC BX
    LOOP NEXT3
NEXT4:MOV CX,OFFSET X1+13
    SUB CX,BX
    CMP CX,5
    JZ NEXT5
    MOV DL,' '
    MOV AH,2H
    INT 21H
    CMP CX,4
    JZ NEXT5
    MOV DL,' '
    MOV AH,2H
    INT 21H
    CMP CX,3
    JZ NEXT5
    MOV DL,' '
    MOV AH,2H
    INT 21H
    CMP CX,2
    JZ NEXT5
    MOV DL,' '
    MOV AH,2H
    INT 21H
NEXT5:MOV DL,[BX];循环显示次数为13-BX中的数
    ADD DL,30H
    MOV AH,2
    INT 21H
    INC BX
    LOOP NEXT5
    MOV AH,4CH
    INT 21H
    MAIN ENDP
    KEYIN PROC;输入子程序
AGAIN:MOV AH,8
    INT 21H
    CMP AL,30H
    JB AGAIN
    CMP AL,39H
    JA AGAIN
    MOV DL,AL
    MOV AH,2
    INT 21H
    RET
    KEYIN ENDP
CODES ENDS
    END START





